name: Deploy to EC2 Chaya
on:
  push:
    branches:
      - chaya_erlanger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_CHAYA }}
          username: ${{ secrets.EC2_USER_CHAYA }}
          key: ${{ secrets.EC2_SSH_KEY_CHAYA }}
          script: |
            cd ~/KonditoriaApp
            git pull origin chaya_erlanger

            cd react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/

            cd ../node.js
            npm install

            sudo systemctl restart bakery.service 
