name: Deploy to EC2

on:
  push:
    branches:
      - chaya_erlanger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_CHAYA }}
          port: 22
          username: ${{ secrets.EC2_USER_CHAYA }}
          key: ${{ secrets.EC2_SSH_KEY_CHAYA }}
          script: |
            cd ~/KonditoriaApp
            git remote set-url origin https://github.com/chaya248/KonditoriaApp.git
            git fetch origin
            git checkout chaya_erlanger || git checkout -b chaya_erlanger origin/chaya_erlanger
            git pull origin chaya_erlanger
            
            # שלבי הבנייה (לפי ההוראות):
            cd react
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            
            cd ../node.js
            npm install
            
            # הפעלה מחדש (אם יש לך service כזה):
            sudo systemctl restart bakery.service || echo "Service not found, skipping"
