name: Deploy to EC2

on:
  push:
    branches:
      - chaya_erlanger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_CHAYA }}
          port: 22
          username: ${{ secrets.EC2_USER_CHAYA }}
          key: ${{ secrets.EC2_SSH_KEY_CHAYA }}
          script: |
            cd ~/KonditoriaApp
            git checkout main
            git fetch origin
            git branch -D chaya_erlanger || true
            git checkout -b chaya_erlanger origin/chaya_erlanger
            git pull origin chaya_erlanger
